fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hard_tabs = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_block_trailing_comma = true
imports_granularity = "Crate"
reorder_impl_items = true
group_imports = "StdExternalCrate"
style_edition = "2024"
tab_spaces = 4
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
